// Quizy/Quizy/Vue/src/components/molecules/TextInput.vue
<template>
  <div class="text-input">
    <label :for="id">{{ label }}</label>
    <input
      class="u-full-width"
      type="text"
      :placeholder="placeholder"
      :id="id"
      :value="value"
      v-on:input="updateValue($event.target.value)"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component
export default class TextInput extends Vue {
  @Prop() public label!: string;
  @Prop() public id!: string;
  @Prop() public value!: string;

  @Prop() public placeholder!: string;
  @Prop() public name?: string;

  updateValue(newValue: string) {
    this.$emit("input", newValue);
  }
}
</script>

<style lang="scss" scoped>
.text-input {
  margin-bottom: 10px;
}
</style>

// Quizy/Quizy/React/src/components/molecules/text-input/text-input.component.tsx
import React, { useState } from 'react';
import { InputChangeEvent } from '../input-change-event.model';
import './text-input.component.scss';

interface Props {
    id: string;
    label: string;
    name?: string;
    placeholder?: string;
    value?: string;

    onValueChange: (event: InputChangeEvent<string>) => void;
}

export const TextInput = (props: Props) => {
    const { id, label, placeholder, name } = props;

    const [value, setValue] = useState(props.value);

    function onValueChange(event: React.FormEvent<HTMLInputElement>) {
        setValue(event.currentTarget.value);
        props.onValueChange({
            name: event.currentTarget.name,
            value: event.currentTarget.value
        });
    }

    return (
        <>
            <div className="text-input">
                <label htmlFor={id}>{label}</label>
                <input
                    type="text"
                    className="u-full-width"
                    placeholder={placeholder}
                    id={id}
                    name={name}
                    value={value}
                    onChange={onValueChange}
                />
            </div>
        </>
    );
}
