// Quizy/Quizy/React/src/components/questions/questions.component.tsx
import React, { useEffect, useState } from 'react';
import './questions.component.scss';
import { useHistory } from 'react-router-dom';
import { Participant } from '../../models/participant.model';
import { Question } from '../../models/question.model';

interface Props {
    participant: Participant | null;
    questions: Array<Question>;
    currentQuestion: Question | null;
    getQuestions: () => void;
    getParticipant: (id: number) => void;
    putParticipant: (participant: Participant) => void;
    clearParticipant: () => void;
    handleAnswer: (score: number) => void;
}

export const Questions = (props: Props) => {
    const { participant, questions, getQuestions, getParticipant, putParticipant, handleAnswer, clearParticipant } = props;

    const [selectedAnswer, setSelectedAnswer] = useState(-1);
    const [currentQuestion, setCurrentQuestion] = useState<Question | null>(props.currentQuestion);
    const history = useHistory();

    useEffect(() => {
        if (participant) {
            getQuestions();
        } else {
            const currentParticipantId = parseInt(localStorage.getItem('currentParticipant') ?? '');
            if (currentParticipantId) {
                getParticipant(currentParticipantId);
            } else {
                history.push('/register');
            }
        }
    }, [participant, getParticipant, getQuestions, history]);

    useEffect(() => {
        if (participant && questions?.length > 0 && !currentQuestion) {
            setCurrentQuestion(questions[participant.questionsAnswered]);
        }
    }, [questions, currentQuestion, participant]);

    function submit() {
        if (!participant) { return; }
        const answer = currentQuestion?.answers.find(a => a.id === selectedAnswer);
        if (answer) {
            handleAnswer(answer.score);
            setSelectedAnswer(-1);
            putParticipant(participant);

            if (participant.questionsAnswered >= questions.length) {
                alert(`That was the last question; Your score was: ${participant.score}; You will be logged out.`);
                clearParticipant();
                localStorage.removeItem('currentParticipant');
                history.push('/register');
            } else {
                setCurrentQuestion(questions[participant.questionsAnswered]);
            }
        }
    }

    function onAnswerChanged(event: React.FormEvent<HTMLInputElement>) {
        setSelectedAnswer(parseInt(event.currentTarget.value));
    }

    return (
        <>
            <div className="container">
                {participant &&
                    <div className="row" id="score-row">
                        <div className="six columns">
                            Your score: {participant.score} points
                        </div>
                    </div>
                }
                {currentQuestion && <>
                    <div className="row">
                        <div className="twelve columns">
                            <h2>
                                {currentQuestion.content}
                                <small>
                                    {participant &&
                                        <span>{participant.questionsAnswered + 1}/{questions.length}</span>
                                    }
                                </small>
                            </h2>
                        </div>
                    </div>
                    {currentQuestion.image &&
                        <div className="row" >
                            <div className="twelve columns">
                                <img src={currentQuestion.image} height="315" alt="qi" />
                            </div>
                        </div>
                    }
                    {currentQuestion.video &&
                        <div className="row">
                            <div className="twelve columns">
                                <iframe
                                    src={currentQuestion.video}
                                    width="560"
                                    height="315"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowFullScreen
                                    title="Question Video">
                                </iframe>
                            </div>
                        </div>
                    }
                    <div className="row">
                        <div className="twelve columns">
                            <p>{currentQuestion.description}</p>
                        </div>
                    </div>
                    <div className="row">
                        <div className="twelve columns">
                            {
                                currentQuestion.answers.map(option => (
                                    <label key={option.id}>
                                        <input type="radio" value={option.id} name="answer" checked={selectedAnswer === option.id} onChange={onAnswerChanged} />
                                        <span className="label-body">{option.text}</span>
                                    </label>
                                ))
                            }
                        </div>
                    </div>
                    <div className="row">
                        <div className="twelve columns">
                            <button disabled={selectedAnswer < 0} onClick={submit}>Submit Answer</button>
                        </div>
                    </div >
                </>}
            </div >
        </>
    );
}

// Quizy/Quizy/Angular/src/app/questions/questions.component.ts
import fromRoot, { AppState } from '../shared/store/selectors';
import { clearParticipant, loadParticipant, updateParticipant } from '../shared/store/actions/participant.action';
import { combineLatest, Subscription } from 'rxjs';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { first } from 'rxjs/operators';
import { loadQuestions } from '../shared/store/actions/questions.action';
import { Question } from '../shared/models/question.model';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';

@Component({
  selector: 'app-questions',
  templateUrl: './questions.component.html',
  styleUrls: ['./questions.component.scss']
})
export class QuestionsComponent implements OnInit, OnDestroy {
  public questions$ = this.store.select(fromRoot.questions.selectQuestionsData);
  public participant$ = this.store.select(fromRoot.participants.selectParticipantData);
  public currentQuestion$ = this.store.select(fromRoot.compound.selectCurrentQuestion);

  public givenAnswer: number;

  private currentQuestionSubscription: Subscription;

  constructor(private store: Store<AppState>, private router: Router, private sanitizer: DomSanitizer) { }

  ngOnDestroy(): void {
    this.currentQuestionSubscription.unsubscribe();
  }

  ngOnInit(): void {
    this.watchQuestionsOrParticipantChange();
    this.resolveParticipant();
    this.store.dispatch(loadQuestions());
  }

  submitAnswer(currentQuestion: Question): void {
    if (currentQuestion) {
      const matchedResult = currentQuestion.answers.find(
        a => a.id === this.givenAnswer
      );

      if (matchedResult) {
        this.givenAnswer = null;
        // Dispatch update for participant
        this.participant$.pipe(first()).subscribe(p => {
          const updatedParticipant = Object.assign({}, p);
          updatedParticipant.score += matchedResult.score;
          updatedParticipant.questionsAnswered++;
          this.store.dispatch(updateParticipant({ participant: updatedParticipant }));
        });

      }
    }
  }

  private resolveParticipant() {
    this.participant$.pipe(first()).subscribe((p) => {
      if (p == null) {
        const rawParcitipantId = localStorage.getItem('currentParticipant');
        if (rawParcitipantId) {
          const participantId = Number.parseInt(rawParcitipantId, 10);
          if (participantId) {
            this.store.dispatch(loadParticipant({ id: participantId }));
            return;
          }
        }
        this.router.navigate(['register']);
      }
    });
  }

  private watchQuestionsOrParticipantChange() {
    this.currentQuestionSubscription = combineLatest([this.participant$, this.questions$]).subscribe(([participant, questions]) => {
      if (participant && questions && questions.length > 0) {
        if (participant.questionsAnswered >= questions.length) {
          alert(
            `That was the last question; Your score was: ${participant.score}; You will be logged out.`
          );
          this.store.dispatch(clearParticipant());
          localStorage.removeItem('currentParticipant');
          this.router.navigate(['register']);
        }
      }
    });
  }
}

<div class="container">
 
  <div class="row" id="score-row" *ngIf="participant$ | async">
    <div class="six columns">
      Your score: {{ (participant$ | async).score }} points
    </div>
  </div>
  <ng-container *ngIf="(currentQuestion$ | async) as currentQuestion">
    <div class="row">
      <div class="twelve columns">
        <h2>
          {{ currentQuestion.content }}
          <small>
            {{ (participant$ | async).questionsAnswered + 1 }}/
            {{ (questions$ | async).length }}
          </small>
        </h2>
      </div>
    </div>
    <div class="row" *ngIf="currentQuestion && currentQuestion.image">
      <div class="twelve columns">
        <img [src]="currentQuestion.image" height="315" alt="qi" />
      </div>
    </div>
    <div class="row" *ngIf="currentQuestion && currentQuestion.video">
      <div class="twelve columns">
        <iframe [src]="currentQuestion.video | safeUrl" width="560" height="315"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
          title="Question Video"></iframe>
      </div>
    </div>
    <div class="row" *ngIf="currentQuestion">
      <div class="twelve columns">
        <p>{{ currentQuestion.description }}</p>
      </div>
    </div>
    <div class="row" *ngIf="currentQuestion">
      <div class="twelve columns">
        <label *ngFor="let answer of currentQuestion.answers">
          <input type="radio" [value]="answer.id" [(ngModel)]="givenAnswer" name="answer" />
          <span class="label-body">{{ answer.text }}</span>
        </label>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns">
        <button [disabled]="!givenAnswer" (click)="submitAnswer(currentQuestion)">
          Submit Answer
        </button>
      </div>
    </div>
  </ng-container>
</div>
