// Quizy/Quizy/Vue/src/components/molecules/TextInput.vue
<template>
  <div class="text-input">
    <label :for="id">{{ label }}</label>
    <input
      class="u-full-width"
      type="text"
      :placeholder="placeholder"
      :id="id"
      :value="value"
      v-on:input="updateValue($event.target.value)"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component
export default class TextInput extends Vue {
  @Prop() public label!: string;
  @Prop() public id!: string;
  @Prop() public value!: string;

  @Prop() public placeholder!: string;
  @Prop() public name?: string;

  updateValue(newValue: string) {
    this.$emit("input", newValue);
  }
}
</script>

<style lang="scss" scoped>
.text-input {
  margin-bottom: 10px;
}
</style>

// Quizy/Quizy/Angular/src/app/shared/components/molecules/text-input/text-input.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output
} from '@angular/core';

@Component({
  selector: 'app-text-input',
  templateUrl: './text-input.component.html',
  styleUrls: ['./text-input.component.scss']
})
export class TextInputComponent {

  @Input() public label!: string;
  @Input() public id!: string;
  @Input() public value!: string;
  @Output() public valueChange: EventEmitter<string> = new EventEmitter();

  @Input() public placeholder!: string;
  @Input() public name?: string;
}

<div class="text-input">
  <label [for]="id">{{ label }}</label>
  <input class="u-full-width" type="text" [placeholder]="placeholder" [id]="id" [ngModel]="value"
    (ngModelChange)="valueChange.emit($event)" />
</div>
