// Quizy/Quizy/React/src/components/questions/questions.component.tsx
import React, { useEffect, useState } from 'react';
import './questions.component.scss';
import { useHistory } from 'react-router-dom';
import { Participant } from '../../models/participant.model';
import { Question } from '../../models/question.model';

interface Props {
    participant: Participant | null;
    questions: Array<Question>;
    currentQuestion: Question | null;
    getQuestions: () => void;
    getParticipant: (id: number) => void;
    putParticipant: (participant: Participant) => void;
    clearParticipant: () => void;
    handleAnswer: (score: number) => void;
}

export const Questions = (props: Props) => {
    const { participant, questions, getQuestions, getParticipant, putParticipant, handleAnswer, clearParticipant } = props;

    const [selectedAnswer, setSelectedAnswer] = useState(-1);
    const [currentQuestion, setCurrentQuestion] = useState<Question | null>(props.currentQuestion);
    const history = useHistory();

    useEffect(() => {
        if (participant) {
            getQuestions();
        } else {
            const currentParticipantId = parseInt(localStorage.getItem('currentParticipant') ?? '');
            if (currentParticipantId) {
                getParticipant(currentParticipantId);
            } else {
                history.push('/register');
            }
        }
    }, [participant, getParticipant, getQuestions, history]);

    useEffect(() => {
        if (participant && questions?.length > 0 && !currentQuestion) {
            setCurrentQuestion(questions[participant.questionsAnswered]);
        }
    }, [questions, currentQuestion, participant]);

    function submit() {
        if (!participant) { return; }
        const answer = currentQuestion?.answers.find(a => a.id === selectedAnswer);
        if (answer) {
            handleAnswer(answer.score);
            setSelectedAnswer(-1);
            putParticipant(participant);

            if (participant.questionsAnswered >= questions.length) {
                alert(`That was the last question; Your score was: ${participant.score}; You will be logged out.`);
                clearParticipant();
                localStorage.removeItem('currentParticipant');
                history.push('/register');
            } else {
                setCurrentQuestion(questions[participant.questionsAnswered]);
            }
        }
    }

    function onAnswerChanged(event: React.FormEvent<HTMLInputElement>) {
        setSelectedAnswer(parseInt(event.currentTarget.value));
    }

    return (
        <>
            <div className="container">
                {participant &&
                    <div className="row" id="score-row">
                        <div className="six columns">
                            Your score: {participant.score} points
                        </div>
                    </div>
                }
                {currentQuestion && <>
                    <div className="row">
                        <div className="twelve columns">
                            <h2>
                                {currentQuestion.content}
                                <small>
                                    {participant &&
                                        <span>{participant.questionsAnswered + 1}/{questions.length}</span>
                                    }
                                </small>
                            </h2>
                        </div>
                    </div>
                    {currentQuestion.image &&
                        <div className="row" >
                            <div className="twelve columns">
                                <img src={currentQuestion.image} height="315" alt="qi" />
                            </div>
                        </div>
                    }
                    {currentQuestion.video &&
                        <div className="row">
                            <div className="twelve columns">
                                <iframe
                                    src={currentQuestion.video}
                                    width="560"
                                    height="315"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowFullScreen
                                    title="Question Video">
                                </iframe>
                            </div>
                        </div>
                    }
                    <div className="row">
                        <div className="twelve columns">
                            <p>{currentQuestion.description}</p>
                        </div>
                    </div>
                    <div className="row">
                        <div className="twelve columns">
                            {
                                currentQuestion.answers.map(option => (
                                    <label key={option.id}>
                                        <input type="radio" value={option.id} name="answer" checked={selectedAnswer === option.id} onChange={onAnswerChanged} />
                                        <span className="label-body">{option.text}</span>
                                    </label>
                                ))
                            }
                        </div>
                    </div>
                    <div className="row">
                        <div className="twelve columns">
                            <button disabled={selectedAnswer < 0} onClick={submit}>Submit Answer</button>
                        </div>
                    </div >
                </>}
            </div >
        </>
    );
}

// Quizy/Quizy/Vue/src/views/Questions.vue
<template>
  <div class="container">
    <div class="row" id="score-row" v-if="this.$store.state.app.participant">
      <div class="six columns">
        Your score: {{ this.$store.state.app.participant.score }} points
      </div>
    </div>
    <div
      class="row"
      v-if="currentQuestion && this.$store.state.app.participant"
    >
      <div class="twelve columns">
        <h2>
          {{ currentQuestion.content }}
          <small>
            {{ this.$store.state.app.participant.questionsAnswered + 1 }}/
            {{ this.$store.state.questions.questions.length }}
          </small>
        </h2>
      </div>
    </div>
    <div class="row" v-if="currentQuestion && currentQuestion.image">
      <div class="twelve columns">
        <img v-bind:src="currentQuestion.image" height="420" alt="qi" />
      </div>
    </div>
    <div class="row" v-if="currentQuestion && currentQuestion.video">
      <div class="twelve columns">
        <iframe
          v-bind:src="currentQuestion.video"
          width="745"
          height="420"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
          title="Question Video"
        ></iframe>
      </div>
    </div>
    <div class="row" v-if="currentQuestion">
      <div class="twelve columns">
        <p>{{ currentQuestion.description }}</p>
      </div>
    </div>
    <div class="row" v-if="currentQuestion">
      <div class="twelve columns">
        <label v-for="option in currentQuestion.answers" v-bind:key="option.id">
          <input type="radio" v-bind:value="option.id" v-model="answer" />
          <span class="label-body">{{ option.text }}</span>
        </label>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns">
        <button :disabled="answer === null" @click="submit">
          Submit Answer
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { Question } from "@/models/Questions";
import { mapGetters } from "vuex";
import Participant from "../models/Participant";

@Component({
  name: "Questions",
  computed: {
    ...mapGetters("app", {
      participant: "participant"
    }),
    ...mapGetters("questions", {
      currentQuestion: "currentQuestion"
    })
  }
})
export default class Questions extends Vue {
  public currentQuestion!: Question;
  public answer: string | null = null;
  private currentQuestionResolved = false;

  // Mapped via computed getters above
  public participant!: Participant;

  created() {
    this.handleLoad();
  }

  async handleLoad() {
    if (!this.$store.getters["app/isParticipantSet"]) {
      await this.$store.dispatch("app/loadParticipant");
    }
    await this.$store.dispatch("questions/load");
  }

  submit() {
    if (this.currentQuestion) {
      const matchedResult = this.currentQuestion.answers.find(
        a => a.id.toString() == this.answer
      );

      if (matchedResult) {
        this.$store.dispatch("app/handleAnswer", matchedResult.score);
        this.answer = null;

        if (
          this.$store.state.app.participant.questionsAnswered >=
          this.$store.state.questions.questions.length
        ) {
          alert(
            `That was the last question; Your score was: ${this.$store.state.app.participant.score}; You will be logged out.`
          );
          this.$store.dispatch("app/clear");
          this.$router.push({ path: "/register" });
        }
      }
    }
  }
}
</script>

<style lang="scss">
h2 > small {
  font-size: 14px;
  color: gray;
}

#score-row {
  border-bottom: 1px solid lightgray;
  padding: 15px 0;
  margin-bottom: 15px;
}
</style>
