// Quizy/Quizy/Vue/src/components/molecules/NumberInput.vue
<template>
  <div class="text-input">
    <label :for="id">{{ label }}</label>
    <input
      class="u-full-width"
      type="number"
      :placeholder="placeholder"
      :id="id"
      :value="value"
      v-on:input="updateValue($event.target.value)"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component
export default class NumberInput extends Vue {
  @Prop() public label!: string;
  @Prop() public id!: string;
  @Prop() public value!: number;

  @Prop() public placeholder!: string;
  @Prop() public name?: string;

  updateValue(newValue: string | number) {
    this.$emit("input", Number(newValue));
  }
}
</script>

<style lang="scss" scoped>
.text-input {
  margin-bottom: 10px;
}
</style>

// Quizy/Quizy/Angular/src/app/shared/components/molecules/number-input/number-input.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output
} from '@angular/core';

@Component({
  selector: 'app-number-input',
  templateUrl: './number-input.component.html',
  styleUrls: ['./number-input.component.scss']
})
export class NumberInputComponent {

  @Input() public label!: string;
  @Input() public id!: string;
  @Input() public value!: number;
  @Output() public valueChange: EventEmitter<number> = new EventEmitter();

  @Input() public placeholder!: string;
  @Input() public name?: string;
}

<div class="number-input">
  <label [for]="id">{{ label }}</label>
  <input class="u-full-width" type="number" [placeholder]="placeholder" [id]="id" [ngModel]="value" (ngModelChange)="valueChange.emit($event)" />
</div>
