// Quizy/Quizy/React/src/components/molecules/number-input/number-input.component.tsx
import React, { useState } from 'react';
import { InputChangeEvent } from '../input-change-event.model';
import './number-input.component.scss';

interface Props {
    id: string;
    label: string;
    placeholder?: string;
    value?: number;

    onValueChange: (value: InputChangeEvent<number>) => void;
}

export const NumberInput = (props: Props) => {
    const { id, label, placeholder } = props;

    const [value, setValue] = useState(props.value);

    function onValueChange(event: React.FormEvent<HTMLInputElement>) {
        const value = parseInt(event.currentTarget.value) || 0;
        setValue(value);
        props.onValueChange({
            value: value,
            name: event.currentTarget.name
        });
    }

    return (
        <>
            <div className="u-full-width">
                <label htmlFor={id}>{label}</label>
                <input
                    type="text"
                    className="u-full-width"
                    placeholder={placeholder}
                    id={id}
                    value={value}
                    onChange={onValueChange}
                />
            </div>
        </>
    );
};

// Quizy/Quizy/Vue/src/components/molecules/NumberInput.vue
<template>
  <div class="text-input">
    <label :for="id">{{ label }}</label>
    <input
      class="u-full-width"
      type="number"
      :placeholder="placeholder"
      :id="id"
      :value="value"
      v-on:input="updateValue($event.target.value)"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component
export default class NumberInput extends Vue {
  @Prop() public label!: string;
  @Prop() public id!: string;
  @Prop() public value!: number;

  @Prop() public placeholder!: string;
  @Prop() public name?: string;

  updateValue(newValue: string | number) {
    this.$emit("input", Number(newValue));
  }
}
</script>

<style lang="scss" scoped>
.text-input {
  margin-bottom: 10px;
}
</style>
