// Quizy/Quizy/React/src/components/header/header.component.tsx
import React from 'react';
import { Link, useHistory } from 'react-router-dom';
import './header.component.scss';
import { Participant } from '../../models/participant.model';

interface Props {
    participant: Participant;
    clearParticipant: () => void;
}

export const Header = (props: Props) => {
    const history = useHistory();

    function logout(event: React.MouseEvent<HTMLDivElement>) {
        localStorage.removeItem('currentParticipant');
        props.clearParticipant();
        history.push('/register');
    }

    return (
        <div id="nav">
            <div className="container">
                <Link to="/questions" id="header-title">Quizy</Link>
                <Link to="/questions">Questions</Link>
                <Link to="/about">About</Link>
                <Link to="/admin">Admin</Link>
                {props.participant &&
                    <div id="current-user" className="u-pull-right" onClick={logout}>
                        Logout {props.participant && props.participant.name}
                    </div>
                }
            </div>
        </div>
    )
}

// Quizy/Quizy/Angular/src/app/shared/components/header/header.component.ts
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
import Participant from '../../models/participant.model';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  @Input() public participant: Participant;
  @Output() public logoutClick: EventEmitter<void> = new EventEmitter();

}

<div id="nav">
  <div class="container">
    <a [routerLink]="['/']" id="header-title">Quizy</a>
    <a [routerLink]="['/questions']">Questions</a>
    <a [routerLink]="['/about']">About</a>
    <a [routerLink]="['/admin/questions']">Admin</a>
    <div id="currentUser" class="u-pull-right" *ngIf="participant" (click)="logoutClick.emit()">
      Logout
      {{ participant.name }}
    </div>
  </div>
</div>
