// Quizy/Quizy/Angular/src/app/shared/components/questions-table/questions-table.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Question } from '../../models/question.model';

@Component({
  selector: 'app-questions-table',
  templateUrl: './questions-table.component.html',
  styleUrls: ['./questions-table.component.scss']
})
export class QuestionsTableComponent {
  @Input() public questions: Question[];
  @Output() public deleteQuestion: EventEmitter<Question> = new EventEmitter();
  @Output() public editQuestion: EventEmitter<Question> = new EventEmitter();
}

<div class="row">
    <div class="twelve columns">
      <table id="questions-table">
        <thead>
          <tr>
            <th id="question-id">#</th>
            <th id="question-content">Content</th>
            <th id="question-description">Description</th>
            <th id="question-actions">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let question of questions">
            <td>{{ question.id }}</td>
            <td>{{ question.content }}</td>
            <td>{{ question.description }}</td>
            <td>
              <button (click)="deleteQuestion.emit(question)">
                <i class="material-icons">delete</i>
              </button>
              <button (click)="editQuestion.emit(question)">
                <i class="material-icons">edit</i>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

// Quizy/Quizy/Vue/src/components/QuestionsTable.vue
<template>
  <div class="row">
    <div class="twelve columns">
      <table id="questions-table">
        <thead>
          <tr>
            <th id="question-id">#</th>
            <th id="question-content">Content</th>
            <th id="question-description">Description</th>
            <th id="question-actions">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="question in questions" v-bind:key="question.id">
            <td>{{ question.id }}</td>
            <td>{{ question.content }}</td>
            <td>{{ question.description }}</td>
            <td>
              <button @click="$emit('deleteQuestion', question)">
                <i class="material-icons">delete</i>
              </button>
              <button @click="$emit('editQuestion', question)">
                <i class="material-icons">edit</i>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";
import { Question } from "@/models/Questions";

@Component
export default class QuestionsTable extends Vue {
  @Prop() public questions!: Question[];
}
</script>

<style lang="scss" scoped>
#questions-table {
  width: 100%;

  td,
  th {
    padding: 10px;
  }
}
</style>
