// Quizy/Quizy/React/src/components/admin/question-form/question-form.component.tsx
import React, { useState } from 'react';
import { Question } from '../../../models';
import { TextInput, InputChangeEvent } from '../../molecules';
import { AdminAnswerRow, AnswerChangeEvent } from '../answer-row/answer-row.component';

interface Props {
    question: Question;
    onChange: (question: Question) => void;
}

export const AdminQuestionForm = (props: Props) => {
    const { onChange } = props;

    const [question, setQuestion] = useState(props.question);

    function onValueChange(event: InputChangeEvent<any>) {
        (question as any)[event.name] = event.value;
        setQuestion(question);
        onChange(question);
    }

    function onAnswerChange(event: AnswerChangeEvent){
        question.answers[event.index] = event.answer;
        setQuestion(question);
        onChange(question);
    }

    return (
        <>
            <div className="row">
                <div className="twelve columns">
                    <TextInput
                        id="question-content"
                        name="content"
                        placeholder="Example question?"
                        label="Content"
                        value={question.content}
                        onValueChange={onValueChange}
                    />
                    <TextInput
                        id="question-description"
                        name="description"
                        placeholder="A description for the question"
                        label="Description"
                        value={question.description}
                        onValueChange={onValueChange}
                    />
                    <TextInput
                        id="question-image"
                        name="image"
                        placeholder="https://image.src/cute-animal.png"
                        label="Image URL"
                        value={question.image}
                        onValueChange={onValueChange}
                    />
                    <TextInput
                        id="question-video"
                        name="video"
                        placeholder="https://www.youtube.com/embed/FeJKJ5MoCHY"
                        label="Video Embed URL"
                        value={question.video}
                        onValueChange={onValueChange}
                    />

                    <hr />
                    <h3>Answers</h3>
                    <AdminAnswerRow answer={question.answers[0]} index={0} onChange={onAnswerChange}/>
                    <AdminAnswerRow answer={question.answers[1]} index={1} onChange={onAnswerChange}/>
                    <AdminAnswerRow answer={question.answers[2]} index={2} onChange={onAnswerChange}/>
                </div>
            </div>
        </>
    )
};

// Quizy/Quizy/Vue/src/components/QuestionForm.vue
<template>
  <div class="row">
    <div class="twelve columns" v-if="value">
      <TextInput
        v-model="value.content"
        id="question-content"
        placeholder="Example question?"
        label="Content"
        @input="updateQuestion"
      />
      <TextInput
        v-model="value.description"
        id="question-description"
        placeholder="A description for the question"
        label="Description"
        @input="updateQuestion"
      />
      <TextInput
        v-model="value.image"
        id="question-image"
        placeholder="https://image.src/cute-animal.png"
        label="Image URL"
        @input="updateQuestion"
      />
      <TextInput
        v-model="value.video"
        id="question-video"
        placeholder="https://www.youtube.com/embed/FeJKJ5MoCHY"
        label="Video Embed URL"
        @input="updateQuestion"
      />

      <hr />
      <h3>Answers</h3>

      <div class="row">
        <div class="eight columns">
          <TextInput
            v-model="value.answers[0].text"
            id="question-answer-0-text"
            placeholder="The answer"
            label="Answer 1"
            @input="updateQuestion"
          />
        </div>
        <div class="four columns">
          <NumberInput
            v-model="value.answers[0].score"
            id="question-answer-0-score"
            placeholder="300"
            label="Score"
            @input="updateQuestion"
          />
        </div>
      </div>

      <div class="row">
        <div class="eight columns">
          <TextInput
            v-model="value.answers[1].text"
            id="question-answer-1-text"
            placeholder="The answer"
            label="Answer 2"
            @input="updateQuestion"
          />
        </div>
        <div class="four columns">
          <NumberInput
            v-model="value.answers[1].score"
            id="question-answer-1-score"
            placeholder="300"
            label="Score"
            @input="updateQuestion"
          />
        </div>
      </div>

      <div class="row">
        <div class="eight columns">
          <TextInput
            v-model="value.answers[2].text"
            id="question-answer-2-text"
            placeholder="The answer"
            label="Answer 3"
            @input="updateQuestion"
          />
        </div>
        <div class="four columns">
          <NumberInput
            v-model="value.answers[2].score"
            id="question-answer-2-score"
            placeholder="300"
            label="Score"
            @input="updateQuestion"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";
import { Question } from "@/models/Questions";
import TextInput from "./molecules/TextInput.vue";
import NumberInput from "./molecules/NumberInput.vue";

@Component({
  components: {
    TextInput,
    NumberInput
  }
})
export default class QuestionForm extends Vue {
  @Prop({
    required: true
  })
  public value!: Question;

  updateQuestion() {
    this.$emit("input", this.value);
  }
}
</script>
